import { Theme } from "@/core/theming/types";

export const lightTheme: Theme = {
    name: "light",
    dark: false,
    colors: {
        primary: {
            50: "#F9F9FF",
            100: "#DFDFFF",
            200: "#C4C4FF",
            300: "#AA80C6",
            400: "#E666FF",
            500: "#DB00FF",
            600: "#C400E6",
            700: "#AA00CC",
            800: "#8800A3",
            900: "#660080",
        },
        secondary: {
            50: "#FFFFFF",
            100: "#F9F9FF",
            200: "#DFDFFF",
            300: "#C4C4C4",
            400: "#AA80C6",
            500: "#6D6D6D",
            600: "#5A5A5A",
            700: "#474747",
            800: "#2C2E32",
            900: "#171819",
        },
        background: {
            primary: "#FFFFFF",
            secondary: "#F9F9FF",
            tertiary: "#DFDFFF",
        },
        surface: {
            primary: "#FFFFFF",
            secondary: "#F9F9FF",
            tertiary: "#DFDFFF",
        },
        text: {
            primary: "#171819",
            secondary: "#2C2E32",
            tertiary: "#6D6D6D",
            inverse: "#FFFFFF",
        },
        border: {
            primary: "#DFDFFF",
            secondary: "#C4C4C4",
            focus: "#DB00FF",
        },
        status: {
            success: "#10b981",
            warning: "#f59e0b",
            error: "#ef4444",
            info: "#DB00FF",
        },
    },
    typography: {
        fontFamily: {
            regular: "System",
            medium: "System",
            semibold: "System",
            bold: "System",
        },
        fontSize: {
            xs: 12,
            sm: 14,
            md: 16,
            lg: 18,
            xl: 20,
            "2xl": 24,
            "3xl": 30,
        },
        lineHeight: {
            tight: 1.2,
            normal: 1.5,
            relaxed: 1.75,
        },
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
        "2xl": 48,
        "3xl": 64,
    },
    borderRadius: {
        none: 0,
        sm: 4,
        md: 8,
        lg: 12,
        xl: 16,
        full: 9999,
    },
};
